export const FETCH_STATISTIC = 'FETCH_STATISTIC';
export const FETCH_STATISTIC_SUCCESS = 'FETCH_STATISTIC_SUCCESS';
export const FETCH_STATISTIC_FAILURE = 'FETCH_STATISTIC_FAILURE';

export const FETCH_ACTIVITY = 'FETCH_ACTIVITY';
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS';
export const FETCH_ACTIVITY_FAILURE = 'FETCH_ACTIVITY_FAILURE';

export const FETCH_STATISTIC_FOR_YEAR = 'FETCH_STATISTIC_FOR_YEAR';
export const FETCH_STATISTIC_FOR_YEAR_SUCCESS = 'FETCH_STATISTIC_FOR_YEAR_SUCCESS';
export const FETCH_STATISTIC_FOR_YEAR_FAILURE = 'FETCH_STATISTIC_FOR_YEAR_FAILURE';

